name: Release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: GoReleaser
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.1
          args: release --clean --config="goreleaser.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
